/**
 * The labelled GitHub corpus — 119 cases.
 *
 * Written by hand, before measuring anything, from the shapes that actually
 * turn up in a working engineer's ninety days: bot spam, dependency churn,
 * typo fixes, a six-PR migration, reviews that were arguments and reviews that
 * were rubber stamps, and about thirty pieces of work someone would genuinely
 * put in a performance review.
 *
 * ── How to read a label ───────────────────────────────────────────────────
 * `verdict` is what the *pipeline* should do:
 *     noise    — filtered by a rule, no model call, no cost
 *     decline  — reaches the model, which should say "this is not a Win"
 *     draft    — becomes a Win draft
 * `acceptable` is a separate, human judgement: would the person who did this
 * work confirm the draft when it lands in their Friday digest? It is deliberately
 * NOT derived from `verdict` — a real accomplishment with a terse description is
 * still acceptable, and a well-described chore still is not.
 *
 * Body text is realistic length on purpose: the §4.3 confidence formula keys off
 * the 200-character boundary, and a corpus of one-line bodies would make that
 * term untested.
 */

import { issue, pr, review, type CorpusCase } from './types';
import { NOISE_RULES } from '@/lib/capture/noise';

const BOT = (note: string) => ({
    verdict: 'noise' as const,
    bot: true,
    acceptable: false,
    rule: NOISE_RULES.botAuthor,
    note,
});

// ═══════════════════════════════════════════════ 1. bots (16) — binary gate

const BOTS: CorpusCase[] = [
    pr({
        id: 'bot-dependabot-lodash',
        title: 'Bump lodash from 4.17.20 to 4.17.21',
        body: 'Bumps [lodash](https://github.com/lodash/lodash) from 4.17.20 to 4.17.21.\n<details>\n<summary>Release notes</summary>\nSourced from lodash releases.\n</details>\nDependabot will resolve any conflicts with this PR as long as you do not alter it yourself.',
        author: 'dependabot[bot]',
        authorType: 'Bot',
        branch: 'dependabot/npm_and_yarn/lodash-4.17.21',
        files: 2,
        adds: 4,
        dels: 4,
        daysAgo: 3,
        label: BOT('the canonical case; if this drafts, the digest is untrustworthy'),
    }),
    pr({
        id: 'bot-dependabot-security',
        title: '[Security] Bump minimist from 1.2.5 to 1.2.6',
        body: 'Bumps minimist from 1.2.5 to 1.2.6. This update includes a security fix for prototype pollution (CVE-2021-44906) with a CVSS score of 9.8.',
        author: 'dependabot[bot]',
        authorType: 'Bot',
        labels: ['dependencies', 'security'],
        daysAgo: 5,
        label: BOT('carries a security label AND a number — must still never draft'),
    }),
    pr({
        id: 'bot-renovate-node',
        title: 'chore(deps): update node.js to v20.11.0',
        body: 'This PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| node | final | minor | 20.9.0 -> 20.11.0 |',
        author: 'renovate[bot]',
        authorType: 'Bot',
        branch: 'renovate/node-20.x',
        daysAgo: 8,
        label: BOT('renovate table format'),
    }),
    pr({
        id: 'bot-renovate-plain-login',
        title: 'Update dependency typescript to v5.6.2',
        body: 'This PR contains the following updates. Automerge enabled.',
        author: 'renovate',
        authorType: 'User',
        daysAgo: 9,
        label: BOT('login is a bot, API reports type User — the login pattern must catch it'),
    }),
    pr({
        id: 'bot-github-actions',
        title: 'Update generated API client',
        body: 'Automated commit from the nightly codegen workflow. No manual changes.',
        author: 'github-actions[bot]',
        authorType: 'Bot',
        files: 41,
        adds: 3_200,
        dels: 2_900,
        daysAgo: 2,
        label: BOT('a large diff authored by CI; size must not rescue it'),
    }),
    pr({
        id: 'bot-github-actions-plain',
        title: 'Regenerate lockfile',
        body: 'Automated by workflow.',
        author: 'github-actions',
        authorType: 'User',
        daysAgo: 11,
        label: BOT('bare github-actions login'),
    }),
    pr({
        id: 'bot-snyk',
        title: '[Snyk] Security upgrade express from 4.17.1 to 4.18.2',
        body: 'Snyk has created this PR to fix one or more vulnerable packages in the npm dependencies of this project.',
        author: 'snyk-bot',
        authorType: 'Bot',
        daysAgo: 14,
        label: BOT('snyk'),
    }),
    pr({
        id: 'bot-imgbot',
        title: '[ImgBot] Optimize images',
        body: '*Total -- 348.24kb -> 271.10kb (22.15%)\n\n/docs/hero.png -- 120.00kb -> 89.00kb (25.83%)',
        author: 'imgbot[bot]',
        authorType: 'Bot',
        daysAgo: 20,
        label: BOT('percentages in the body — a bot with tempting numbers'),
    }),
    pr({
        id: 'bot-mergify',
        title: 'Merge queue: embarking main (a1b2c3d)',
        body: 'This pull request has been created by Mergify to speculatively check the mergeability.',
        author: 'mergify[bot]',
        authorType: 'Bot',
        daysAgo: 4,
        label: BOT('merge queue noise'),
    }),
    pr({
        id: 'bot-codecov',
        title: 'Update coverage badge',
        body: 'Coverage increased from 81.2% to 83.7%.',
        author: 'codecov-commenter',
        authorType: 'User',
        daysAgo: 17,
        label: BOT('codecov posts as a user account'),
    }),
    pr({
        id: 'bot-semantic-release',
        title: 'chore(release): 2.14.0 [skip ci]',
        body: '# [2.14.0](https://github.com/acme/api/compare/v2.13.0...v2.14.0) (2026-07-14)\n\n### Features\n* pricing batch lookups',
        author: 'semantic-release-bot',
        authorType: 'Bot',
        daysAgo: 17,
        label: BOT('release automation'),
    }),
    pr({
        id: 'bot-whitesource',
        title: 'WS-2026-0001: Upgrade axios to 1.7.4',
        body: 'WhiteSource Bolt detected a vulnerable dependency.',
        author: 'whitesource-bolt-for-github[bot]',
        authorType: 'Bot',
        daysAgo: 25,
        label: BOT('whitesource'),
    }),
    pr({
        id: 'bot-vercel',
        title: 'Preview deployment for feature/pricing',
        body: 'The latest updates on your projects.',
        author: 'vercel[bot]',
        authorType: 'Bot',
        daysAgo: 6,
        label: BOT('deploy previews'),
    }),
    pr({
        id: 'bot-stale',
        title: 'Close stale pull requests',
        body: 'This PR has been automatically closed due to inactivity.',
        author: 'stale[bot]',
        authorType: 'Bot',
        daysAgo: 30,
        label: BOT('stale bot'),
    }),
    pr({
        id: 'bot-internal-release',
        title: 'Publish 2026.07.3 to the internal registry',
        body: 'Automated publish job. Version bumped from 2026.07.2 to 2026.07.3 and artefacts pushed to the internal npm registry. No human changes in this PR.',
        author: 'acme-release-bot',
        authorType: 'User',
        daysAgo: 13,
        label: BOT('company-specific bot with a -bot suffix and a plausible human-sounding title'),
    }),
    pr({
        id: 'bot-typed-only',
        title: 'Sync translations from Crowdin',
        body: 'New translations have been pulled from Crowdin for 14 locales. This includes 320 new strings across the checkout and onboarding flows.',
        author: 'crowdin-sync',
        authorType: 'Bot',
        files: 28,
        adds: 640,
        dels: 120,
        daysAgo: 7,
        label: BOT('only the API type says bot; the login looks human-ish'),
    }),
];

// ═══════════════════════════════ 2. human dependency / chore churn (7)

const CHORES: CorpusCase[] = [
    pr({
        id: 'chore-bump-node-human',
        title: 'chore(ci): bump node from 18 to 20 in the build image',
        body: 'Updates the CI base image so we stop getting the deprecation warning on every run.',
        daysAgo: 12,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.choreTitle,
            note: 'a human did it, but it is still a bump. The chore(...) prefix fires before the bump pattern, which is fine: both are layer-1 drops.',
        },
    }),
    pr({
        id: 'chore-deps-build',
        title: 'build(deps): upgrade webpack to 5.92.1',
        body: 'Routine upgrade.',
        daysAgo: 15,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.dependencyBump,
            note: 'build(deps) prefix',
        },
    }),
    pr({
        id: 'chore-docs-readme',
        title: 'docs: fix the local setup instructions',
        body: 'The README told people to run a script that we deleted in March.',
        daysAgo: 22,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.choreTitle,
            note: 'docs: prefix — real but not a Win',
        },
    }),
    pr({
        id: 'chore-ci-cache',
        title: 'ci: cache the pnpm store between jobs',
        body: 'Adds an actions/cache step keyed on the lockfile hash.',
        daysAgo: 19,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: true,
            rule: NOISE_RULES.choreTitle,
            note: 'ARGUABLE: a genuine CI speedup, lost to the ci: prefix. Precision cost we accept.',
        },
    }),
    pr({
        id: 'chore-update-eslint',
        title: 'Update eslint config to v9',
        body: 'Flat config migration.',
        daysAgo: 26,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.dependencyBump,
            note: '"Update x to v9" matches the bump pattern',
        },
    }),
    pr({
        id: 'chore-bump-terraform',
        title: 'Bump terraform provider aws from 5.40 to 5.55',
        body: 'Needed for the new instance type.',
        daysAgo: 28,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.dependencyBump,
            note: 'bump ... from ... to',
        },
    }),
    pr({
        id: 'chore-build-scope',
        title: 'build: split the Dockerfile into a builder stage',
        body: 'Multi-stage build so the runtime image no longer ships the toolchain. Image size drops from 1.2GB to 340MB, which makes cold starts noticeably faster on the workers.',
        files: 3,
        adds: 40,
        dels: 30,
        daysAgo: 31,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: true,
            rule: NOISE_RULES.choreTitle,
            note: 'ARGUABLE and the most expensive miss in this group: a real, quantified infra win behind a build: prefix',
        },
    }),
];

// ═══════════════════════════ 3. merges, reverts, release branches, empties (7)

const MECHANICAL: CorpusCase[] = [
    pr({
        id: 'mech-merge-branch',
        title: 'Merge branch main into feature/pricing',
        body: '',
        daysAgo: 9,
        label: { verdict: 'noise', bot: false, acceptable: false, rule: NOISE_RULES.mergeCommit, note: '' },
    }),
    pr({
        id: 'mech-merge-pr',
        title: 'Merge pull request #4821 from acme/hotfix-checkout',
        body: '',
        daysAgo: 10,
        label: { verdict: 'noise', bot: false, acceptable: false, rule: NOISE_RULES.mergeCommit, note: '' },
    }),
    pr({
        id: 'mech-revert-own',
        title: 'Revert "Batch pricing lookups in the checkout path"',
        body: 'This reverts commit 8f3a1c2. The batch query regressed p99 on the read replica.',
        daysAgo: 6,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.revertOwn,
            note: 'reverting your own PR is not a second Win',
        },
    }),
    pr({
        id: 'mech-release-branch',
        title: 'Release 2026.07',
        body: 'Cuts the July release branch.',
        branch: 'release/2026.07',
        daysAgo: 21,
        label: { verdict: 'noise', bot: false, acceptable: false, rule: NOISE_RULES.releaseBranch, note: '' },
    }),
    pr({
        id: 'mech-hotfix-branch',
        title: 'Hotfix the checkout timeout',
        body: 'Cherry-picked onto the release branch.',
        branch: 'hotfix/checkout-timeout',
        daysAgo: 23,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: true,
            rule: NOISE_RULES.releaseBranch,
            note: 'ARGUABLE: a real hotfix, filtered by branch convention',
        },
    }),
    pr({
        id: 'mech-empty-diff',
        title: 'Trigger a rebuild',
        body: '',
        adds: 0,
        dels: 0,
        files: 0,
        daysAgo: 16,
        label: { verdict: 'noise', bot: false, acceptable: false, rule: NOISE_RULES.noNetChange, note: '' },
    }),
    pr({
        id: 'mech-revert-someone-else',
        title: 'Revert "Enable the new pricing engine for everyone"',
        body: 'Rolling back the flag rollout after error rates on the pricing service went from 0.1% to 4.2% within ten minutes of the ramp. Incident PRC-118. We will re-enable behind a per-tenant flag once the caching bug is fixed.',
        author: 'maya-dev',
        labels: ['incident'],
        comments: 4,
        daysAgo: 5,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: true,
            rule: NOISE_RULES.revertOwn,
            note: 'ARGUABLE: incident response framed as a revert. Documented precision cost of the revert rule.',
        },
    }),
];

// ═══════════════════════════════════════ 4. trivial / low-signal (12)

const TRIVIAL: CorpusCase[] = [
    pr({
        id: 'triv-typo',
        title: 'Fix typo',
        body: '',
        adds: 1,
        dels: 1,
        files: 1,
        daysAgo: 4,
        label: { verdict: 'decline', bot: false, acceptable: false, note: 'the §4.2 rule-1 canonical case' },
    }),
    pr({
        id: 'triv-typo-in-comment',
        title: 'fix typo in comment',
        body: '',
        adds: 1,
        dels: 1,
        daysAgo: 8,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-wip',
        title: 'WIP',
        body: '',
        daysAgo: 11,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-fix',
        title: 'fix',
        body: '',
        daysAgo: 13,
        label: { verdict: 'decline', bot: false, acceptable: false, note: 'title "fix", empty body — §4.2 rule 1 verbatim' },
    }),
    pr({
        id: 'triv-cleanup',
        title: 'cleanup',
        body: '',
        adds: 12,
        dels: 40,
        daysAgo: 18,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-lint',
        title: 'lint',
        body: '',
        files: 30,
        adds: 200,
        dels: 200,
        daysAgo: 24,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-nit',
        title: 'nit: rename variable',
        body: '',
        daysAgo: 27,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-formatting',
        title: 'formatting only',
        body: '',
        files: 55,
        adds: 900,
        dels: 900,
        daysAgo: 29,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-tests',
        title: 'tests',
        body: '',
        daysAgo: 33,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-rename-file',
        title: 'rename file',
        body: '',
        daysAgo: 35,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'triv-cleanup-that-mattered',
        title: 'Cleanup: delete the legacy billing importer',
        body: 'Removes the 2019 CSV importer and its three cron jobs. Nothing has called it since the Stripe migration finished, and it was the last thing holding us to the old `billing_legacy` schema, which this also drops. Coordinated with finance so the monthly reconciliation job now reads from the new tables.',
        files: 22,
        adds: 30,
        dels: 3_140,
        labels: ['refactor'],
        comments: 3,
        daysAgo: 36,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: '§6.4 exists for this: sometimes "cleanup" is a 3,000-line deletion that mattered. Penalty, not exclusion.',
        },
    }),
    pr({
        id: 'triv-small-but-described',
        title: 'Fix off-by-one in the pagination cursor',
        body: 'The cursor was inclusive on one side and exclusive on the other, so the last item of every page reappeared as the first item of the next. Two-character fix, plus a regression test that would have caught it.',
        adds: 34,
        dels: 4,
        labels: ['bug'],
        daysAgo: 37,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: 'tiny diff, real bug, described properly — must survive',
        },
    }),
];

// ═════════════════════════════════ 5. strong, quantified work (16)

const QUANTIFIED: CorpusCase[] = [
    pr({
        id: 'q-checkout-latency',
        title: 'Batch pricing lookups in the checkout path',
        body: 'Checkout was issuing one pricing query per line item, so a 30-item cart meant 30 round trips to the pricing service. This batches them into a single call with an in-request cache. p95 checkout latency drops from 800ms to 180ms in staging under the replayed peak traffic profile.',
        labels: ['performance', 'backend'],
        files: 7,
        adds: 210,
        dels: 340,
        comments: 4,
        issue: {
            number: 1190,
            title: 'Checkout times out during peak',
            body: 'During Monday peaks we see checkout requests exceeding the 2s gateway timeout. Support has 14 tickets this month.',
        },
        dirs: ['src/checkout'],
        daysAgo: 17,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'the PRD §4.2 worked example' },
    }),
    pr({
        id: 'q-index-p99',
        title: 'Add a covering index for the tenant activity query',
        body: 'The activity feed query was doing a sequential scan on a 40 million row table. Adding a covering index on (tenant_id, created_at desc) takes the p99 from 3.4s to 90ms. Migration runs concurrently so there is no write lock.',
        labels: ['performance', 'database'],
        files: 3,
        adds: 60,
        dels: 5,
        comments: 5,
        dirs: ['db/migrations'],
        daysAgo: 20,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-image-pipeline',
        title: 'Move thumbnail generation to a background worker',
        body: 'Uploads were generating four thumbnail sizes synchronously, which is why the upload endpoint had a 6 second p95. Generation now happens in a worker and the client polls. Upload p95 is 400ms. Also cuts the API pod memory ceiling from 2GB to 700MB since we no longer hold decoded images in the request path.',
        labels: ['performance'],
        files: 12,
        adds: 430,
        dels: 180,
        comments: 6,
        dirs: ['src/media'],
        daysAgo: 24,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'two independent measurements' },
    }),
    pr({
        id: 'q-cost-s3',
        title: 'Lifecycle-expire raw event blobs after 30 days',
        body: 'We were keeping every raw webhook payload forever. Nothing reads them past the replay window. A lifecycle rule expires them at 30 days, which takes the bucket from 41TB to about 3TB and roughly $940 a month off the storage line.',
        labels: ['cost', 'infrastructure'],
        files: 2,
        adds: 45,
        dels: 0,
        comments: 2,
        dirs: ['infra/storage'],
        daysAgo: 26,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'currency and size units' },
    }),
    pr({
        id: 'q-flaky-tests',
        title: 'Make the integration suite deterministic',
        body: 'The integration suite was failing about 1 in 5 runs, which meant nobody trusted a red build. Root causes were a shared Redis database between parallel workers and two tests that depended on wall-clock ordering. Suite has now run 200 times green.',
        labels: ['reliability'],
        files: 18,
        adds: 260,
        dels: 190,
        comments: 3,
        dirs: ['test/integration'],
        daysAgo: 29,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'a fraction and a count' },
    }),
    pr({
        id: 'q-onboarding-steps',
        title: 'Collapse onboarding from seven steps to three',
        body: 'Merged the profile, preferences and notification steps into one screen and deferred workspace setup until first use. Activation in the experiment arm went from 41% to 58% over two weeks.',
        labels: ['feature', 'ux'],
        files: 14,
        adds: 380,
        dels: 520,
        comments: 8,
        dirs: ['src/onboarding'],
        daysAgo: 31,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-rate-limiter',
        title: 'Replace the fixed-window rate limiter with a sliding window',
        body: 'The fixed window let a client burst 2x the configured limit across a boundary. Sliding window with a Redis sorted set fixes it. Verified with a load test at 1000 rps against a 500 rps limit.',
        labels: ['reliability', 'api'],
        files: 6,
        adds: 190,
        dels: 130,
        comments: 4,
        dirs: ['src/api'],
        daysAgo: 33,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-bundle-size',
        title: 'Code-split the admin console out of the main bundle',
        body: 'Admin routes were being shipped to every user. Dynamic import behind the route boundary takes the initial JS from 1.4MB to 620KB, and Lighthouse TTI on a throttled connection improves from 8.2s to 4.9s.',
        labels: ['performance', 'frontend'],
        files: 9,
        adds: 140,
        dels: 60,
        comments: 3,
        dirs: ['src/app'],
        daysAgo: 38,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-queue-backlog',
        title: 'Shard the notification queue by tenant',
        body: 'A single noisy tenant could fill the queue and delay everyone. Sharding by tenant hash across 8 partitions means the worst-case delay for an unrelated tenant went from 40 minutes to under 30 seconds during the same replayed incident.',
        labels: ['reliability', 'infrastructure'],
        files: 11,
        adds: 300,
        dels: 90,
        comments: 5,
        dirs: ['src/notifications'],
        daysAgo: 41,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-support-tickets',
        title: 'Show the real reason a payment failed',
        body: 'We were collapsing every Stripe decline into "Payment failed". Now we map the decline codes to specific copy with a next action. Support volume for payment questions dropped by about a third in the first two weeks.',
        labels: ['feature', 'ux'],
        files: 8,
        adds: 220,
        dels: 70,
        comments: 4,
        issue: {
            number: 2041,
            title: 'Users cannot tell why their card was declined',
            body: 'Payment-related tickets are 18% of all support volume and most of them are "why did my card fail".',
        },
        dirs: ['src/billing'],
        daysAgo: 44,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'written fraction ("a third") plus a linked-issue percentage' },
    }),
    pr({
        id: 'q-cold-start',
        title: 'Lazy-load the ML model in the scoring worker',
        body: 'The worker was loading a 700MB model at import time, so every cold start took 45 seconds and the autoscaler kept killing pods before they were ready. Loading on first use behind a mutex brings cold start to 3 seconds.',
        labels: ['performance'],
        files: 4,
        adds: 95,
        dels: 30,
        comments: 2,
        dirs: ['src/scoring'],
        daysAgo: 47,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-api-errors',
        title: 'Return structured errors from the public API',
        body: 'Every error was a 500 with a string. The API now returns an RFC 7807 problem document with a stable code. Integration partners had been raising this for months; the two largest have already switched their retry logic to key off the code instead of the message.',
        labels: ['api', 'feature'],
        files: 26,
        adds: 610,
        dels: 240,
        comments: 9,
        dirs: ['src/api'],
        daysAgo: 50,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'the only numbers are an RFC number and "two" — a good guard test' },
    }),
    pr({
        id: 'q-db-connections',
        title: 'Introduce PgBouncer in transaction mode',
        body: 'Connection count against the primary was hitting the 500 ceiling during deploys because every pod opened its own pool. PgBouncer in transaction mode holds it at about 60 regardless of pod count.',
        labels: ['infrastructure', 'reliability'],
        files: 7,
        adds: 180,
        dels: 40,
        comments: 6,
        dirs: ['infra/db'],
        daysAgo: 53,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-search-relevance',
        title: 'Rerank search results by recency-weighted relevance',
        body: 'Pure BM25 was surfacing three-year-old documents above last week\'s. Added a recency decay term with a 90 day half-life. Click-through on the first result went from 22% to 35% in the holdout.',
        labels: ['feature', 'data'],
        files: 5,
        adds: 160,
        dels: 45,
        comments: 4,
        dirs: ['src/search'],
        daysAgo: 56,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-incident-postmortem',
        title: 'Add idempotency keys to the payment capture endpoint',
        body: 'Follow-up from the June 3rd incident where a client retry double-charged 47 customers. Capture now requires an idempotency key and stores the response for 24 hours. Backfilled refunds are tracked separately in FIN-882.',
        labels: ['bug', 'security'],
        files: 9,
        adds: 240,
        dels: 60,
        comments: 7,
        dirs: ['src/billing'],
        daysAgo: 58,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'q-accessibility',
        title: 'Make the data table keyboard navigable',
        body: 'The table was a div soup with no roles, so screen readers announced nothing and tab order skipped it entirely. Rebuilt on a real table element with proper roles and roving tabindex. Fixes 31 of the 34 axe violations on the dashboard.',
        labels: ['accessibility', 'frontend'],
        files: 13,
        adds: 340,
        dels: 280,
        comments: 5,
        dirs: ['src/components'],
        daysAgo: 61,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
];

// ═══════════════════════════ 6. strong, unquantified work (16)

const UNQUANTIFIED: CorpusCase[] = [
    pr({
        id: 'u-multi-region',
        title: 'Make the session store region-aware',
        body: 'Sessions were pinned to a single region, so a failover logged everyone out. The store now replicates session state and reads locally with a fallback to the primary region. This is the last piece needed before we can run active-active.',
        labels: ['infrastructure', 'reliability'],
        files: 16,
        adds: 520,
        dels: 210,
        comments: 7,
        dirs: ['src/auth'],
        daysAgo: 18,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'no figure anywhere — must draft with quantified=false and a prompt' },
    }),
    pr({
        id: 'u-audit-log',
        title: 'Add an append-only audit log for admin actions',
        body: 'Every admin mutation now writes an immutable audit record with the actor, the before and after state and a request id. Required for the SOC 2 control we failed on last cycle. Records are written in the same transaction as the change, so there is no window where an action exists without its log entry.',
        labels: ['security', 'feature'],
        files: 21,
        adds: 640,
        dels: 80,
        comments: 8,
        dirs: ['src/admin'],
        daysAgo: 21,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-feature-flags',
        title: 'Replace the config-file flags with a runtime flag service',
        body: 'Flags lived in a YAML file that required a deploy to change, which meant every experiment took a release. Flags now resolve from a service with a local cache and a 30 second TTL, and the SDK falls back to the last known good value if the service is unreachable.',
        labels: ['infrastructure'],
        files: 19,
        adds: 580,
        dels: 320,
        comments: 6,
        dirs: ['src/platform'],
        daysAgo: 27,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'contains "30 second" — a real figure, must survive the guard' },
    }),
    pr({
        id: 'u-schema-migration-tooling',
        title: 'Add expand-contract migration tooling',
        body: 'We had no safe way to rename a column without downtime. This adds a two-phase migration runner and a lint rule that rejects a destructive migration unless a matching expand migration shipped in an earlier release.',
        labels: ['infrastructure', 'database'],
        files: 15,
        adds: 470,
        dels: 60,
        comments: 5,
        dirs: ['db/tooling'],
        daysAgo: 34,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-webhooks-retry',
        title: 'Give outbound webhooks a proper retry policy',
        body: 'Webhook delivery was fire and forget, so a customer endpoint being down for a minute silently lost events. Deliveries now go through the job queue with exponential backoff and a dead-letter view customers can inspect and replay themselves.',
        labels: ['reliability', 'feature'],
        files: 12,
        adds: 390,
        dels: 110,
        comments: 4,
        dirs: ['src/webhooks'],
        daysAgo: 39,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-design-system-tokens',
        title: 'Move colour and spacing to design tokens',
        body: 'Component styles were hardcoding hex values, which is why dark mode was half-broken and nobody wanted to touch it. Everything now resolves from a token layer, and dark mode is a token swap rather than a per-component override.',
        labels: ['design', 'frontend'],
        files: 47,
        adds: 900,
        dels: 1_100,
        comments: 6,
        dirs: ['src/components'],
        daysAgo: 42,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-oncall-runbook',
        title: 'Wire alerts to runbooks and page the right team',
        body: 'Alerts were all going to one channel with no context, so the first ten minutes of every incident were spent working out who owned the thing. Each alert now carries an owner, a runbook link and a severity that drives the paging policy.',
        labels: ['observability', 'reliability'],
        files: 24,
        adds: 410,
        dels: 90,
        comments: 3,
        dirs: ['infra/monitoring'],
        daysAgo: 45,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '"ten minutes" is in the body — usable' },
    }),
    pr({
        id: 'u-graphql-n1',
        title: 'Add dataloaders to the GraphQL resolvers',
        body: 'Nested resolvers were issuing a query per node. Dataloaders batch within a request. This also lets us drop the ad-hoc caching layer that was papering over it and occasionally serving a stale tenant name.',
        labels: ['performance', 'api'],
        files: 17,
        adds: 430,
        dels: 260,
        comments: 5,
        dirs: ['src/graphql'],
        daysAgo: 48,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-mobile-offline',
        title: 'Make the mobile client work offline',
        body: 'Reads now come from a local store that syncs in the background, and writes queue until connectivity returns with a last-writer-wins merge. Field users on bad connections were the loudest request in the last two research rounds.',
        labels: ['feature'],
        files: 33,
        adds: 1_200,
        dels: 340,
        comments: 11,
        dirs: ['mobile/sync'],
        daysAgo: 51,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-secrets-rotation',
        title: 'Rotate service credentials automatically',
        body: 'Service credentials were created by hand and never rotated; two of them predated everyone currently on the team. Credentials are now issued by the secrets manager with a short lease and rotated on a schedule, and the app reloads them without a restart.',
        labels: ['security', 'infrastructure'],
        files: 14,
        adds: 380,
        dels: 120,
        comments: 6,
        dirs: ['infra/secrets'],
        daysAgo: 54,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-error-budget',
        title: 'Define SLOs for the three customer-facing endpoints',
        body: 'We had dashboards but no agreement on what good looked like, so every latency conversation restarted from scratch. This adds availability and latency SLOs with error budgets, and a burn-rate alert that fires before the budget is gone rather than after.',
        labels: ['observability'],
        files: 8,
        adds: 260,
        dels: 20,
        comments: 4,
        dirs: ['infra/monitoring'],
        daysAgo: 57,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-tenant-isolation',
        title: 'Enforce tenant isolation at the query layer',
        body: 'Tenant scoping was a convention every query had to remember, and we had already had one near miss. Scoping is now enforced by the data-access layer and a test fails the build if a query reaches the database without a tenant predicate.',
        labels: ['security', 'architecture'],
        files: 29,
        adds: 700,
        dels: 400,
        comments: 9,
        dirs: ['src/data'],
        daysAgo: 60,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-import-wizard',
        title: 'Build a CSV import wizard with a dry-run preview',
        body: 'Imports were a support task because the endpoint failed on the first bad row with a stack trace. The wizard validates the whole file first, shows exactly which rows will fail and why, and lets the user fix and re-upload before anything is written.',
        labels: ['feature', 'ux'],
        files: 20,
        adds: 810,
        dels: 60,
        comments: 7,
        dirs: ['src/import'],
        daysAgo: 63,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    pr({
        id: 'u-terse-but-real',
        title: 'Add read-replica routing for analytics queries',
        body: 'Analytics reads now go to the replica.',
        labels: ['performance', 'database'],
        files: 5,
        adds: 120,
        dels: 30,
        comments: 2,
        dirs: ['src/data'],
        daysAgo: 66,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: 'terse body, real work — recall over precision at draft time (§1)',
        },
    }),
    pr({
        id: 'u-issue-carries-the-why',
        title: 'Cache the entitlement lookup',
        body: 'Adds a per-request memo.',
        labels: ['performance'],
        files: 3,
        adds: 70,
        dels: 15,
        comments: 1,
        issue: {
            number: 3310,
            title: 'Dashboard is slow for enterprise accounts',
            body: 'Accounts with many seats see the dashboard take several seconds. Profiling shows the entitlement check running once per widget, so a 12-widget dashboard does 12 identical lookups.',
        },
        dirs: ['src/platform'],
        daysAgo: 69,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: '§4.2 rule 2: the "so what" is only in the linked issue',
        },
    }),
    pr({
        id: 'u-mentoring-doc',
        title: 'Write the service ownership guide for new joiners',
        body: 'Documents which team owns which service, how to get access, and what to do when a service you do not own is on fire. Written after watching three new joiners each independently spend a day finding this out.',
        labels: ['docs'],
        files: 4,
        adds: 300,
        dels: 10,
        comments: 5,
        dirs: ['docs/onboarding'],
        daysAgo: 72,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: 'labelled docs but the title is not a docs: prefix — should survive and categorise as influenced/grew',
        },
    }),
];

// ═══════════════════════════════════ 7. bulk / mechanical at scale (5)

const BULK: CorpusCase[] = [
    pr({
        id: 'bulk-prettier',
        title: 'Apply the new prettier config across the repo',
        body: 'Mechanical reformat. No behaviour change. Reviewed by scanning the diff for anything that is not whitespace.',
        files: 812,
        adds: 24_000,
        dels: 23_800,
        daysAgo: 30,
        label: {
            verdict: 'decline',
            bot: false,
            acceptable: false,
            note: 'the -0.20 bulk penalty plus an honest "no behaviour change" body',
        },
    }),
    pr({
        id: 'bulk-license-headers',
        title: 'Add license headers to every source file',
        body: 'Adds the SPDX header. Generated by a script.',
        files: 640,
        adds: 1_280,
        dels: 0,
        daysAgo: 43,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'bulk-import-sort',
        title: 'Sort imports repo-wide',
        body: '',
        files: 430,
        adds: 2_100,
        dels: 2_100,
        daysAgo: 46,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
    pr({
        id: 'bulk-monorepo-move',
        title: 'Move packages into the pnpm workspace layout',
        body: 'Physically relocates twelve packages under packages/ and rewrites every relative import. The interesting part is the codemod, which is committed under tools/, and the CI change that now builds only the affected packages — CI time on a typical PR goes from 22 minutes to about 6.',
        files: 1_100,
        adds: 31_000,
        dels: 30_800,
        labels: ['infrastructure', 'refactor'],
        comments: 12,
        daysAgo: 49,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: 'huge diff, but the description carries a real outcome. Bulk penalty must not be fatal.',
        },
    }),
    pr({
        id: 'bulk-typescript-strict',
        title: 'Turn on strict mode and fix the fallout',
        body: 'Enables strict null checks. The fallout was 1,340 errors across 380 files, most of them genuinely missing null handling in code paths we had never tested. Three of them were real bugs, listed in the description of the linked issue.',
        files: 380,
        adds: 4_200,
        dels: 3_900,
        labels: ['refactor', 'reliability'],
        comments: 9,
        issue: {
            number: 4001,
            title: 'Enable TypeScript strict mode',
            body: 'Tracking issue. Three real bugs found: the null tenant in billing export, the undefined cursor in search, the missing guard in the webhook signer.',
        },
        daysAgo: 52,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
];

// ═══════════════════ 8. one effort spread across several PRs (9)

const GROUPED: CorpusCase[] = [
    ...[1, 2, 3, 4, 5, 6].map((part) =>
        pr({
            id: `group-payments-${part}`,
            groupWith: 'payments-migration',
            title: `Migrate payments module to the new ledger (${part}/6)`,
            body: `Part ${part} of the ledger migration. Moves another slice of the payments module onto the double-entry ledger, keeping the old writer in place behind a comparison harness so we can diff the two for a week before cutting over.`,
            repo: 'acme/api',
            labels: ['migration', 'backend'],
            files: 9 + part,
            adds: 300,
            dels: 240,
            comments: 3,
            dirs: ['src/payments'],
            daysAgo: 20 - part,
            label: {
                verdict: 'draft',
                bot: false,
                acceptable: true,
                note: 'six PRs, one effort — §4.1 must collapse these into a single candidate',
            },
        }),
    ),
    ...[1, 2, 3].map((part) =>
        pr({
            id: `group-search-${part}`,
            groupWith: 'search-rewrite',
            title: `Rewrite search indexing pipeline (step ${part})`,
            body: `Step ${part} of replacing the nightly full reindex with an incremental indexing pipeline driven off the change feed. This step keeps both paths live and compares their output.`,
            repo: 'acme/api',
            labels: ['data', 'performance'],
            files: 12,
            adds: 400,
            dels: 150,
            comments: 4,
            dirs: ['src/search'],
            daysAgo: 40 - part * 2,
            label: {
                verdict: 'draft',
                bot: false,
                acceptable: true,
                note: 'three PRs, one effort',
            },
        }),
    ),
];

// ═══════════════════════════════════════════════ 9. reviews (14)

const REVIEWS: CorpusCase[] = [
    review({
        id: 'rev-lgtm',
        title: 'Add a retry to the export job',
        reviewBody: 'LGTM',
        state: 'APPROVED',
        daysAgo: 3,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.reviewNotSubstantive,
            note: '§12: a pr_reviewed signal with only "LGTM" produces no draft',
        },
    }),
    review({
        id: 'rev-lgtm-emoji',
        title: 'Bump the worker concurrency',
        reviewBody: '👍',
        state: 'APPROVED',
        daysAgo: 6,
        label: { verdict: 'noise', bot: false, acceptable: false, rule: NOISE_RULES.reviewNotSubstantive, note: '' },
    }),
    review({
        id: 'rev-ship-it',
        title: 'Update the copy on the empty state',
        reviewBody: 'ship it',
        state: 'APPROVED',
        daysAgo: 9,
        label: { verdict: 'noise', bot: false, acceptable: false, rule: NOISE_RULES.reviewNotSubstantive, note: '' },
    }),
    review({
        id: 'rev-nice-thanks',
        title: 'Add the missing index',
        reviewBody: 'nice, thanks',
        state: 'APPROVED',
        daysAgo: 12,
        label: { verdict: 'noise', bot: false, acceptable: false, rule: NOISE_RULES.reviewNotSubstantive, note: '' },
    }),
    review({
        id: 'rev-long-quote-lgtm',
        title: 'Refactor the pricing resolver',
        reviewBody:
            '```suggestion\nconst price = await pricing.batch(ids);\n```\n> we should probably batch these\n\nLGTM',
        state: 'APPROVED',
        daysAgo: 15,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.reviewNotSubstantive,
            note: 'clears 120 chars only via a quoted diff — the substance strip must catch it',
        },
    }),
    review({
        id: 'rev-substantive-locking',
        title: 'Add a scheduled cleanup job',
        reviewBody:
            'This takes a table-level lock for the duration of the delete, which on the events table means blocking every write for as long as the delete runs. Suggest batching in chunks of a few thousand with a short sleep between batches, and adding a guard so it stops if replication lag goes above a second. Otherwise the first time this runs against production volume it will look like an outage.',
        state: 'CHANGES_REQUESTED',
        comments: 2,
        daysAgo: 7,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: 'the category people always forget — influenced',
        },
    }),
    review({
        id: 'rev-substantive-api-shape',
        title: 'Add the bulk update endpoint',
        reviewBody:
            'Two things about the shape. Returning 200 with a per-item status array means clients have to parse the body to know whether anything failed, and most of them will not. 207 with the same array is the honest answer. Second, the endpoint takes an unbounded array; we should cap it and document the cap rather than discovering it as a timeout in production.',
        state: 'CHANGES_REQUESTED',
        comments: 3,
        daysAgo: 11,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    review({
        id: 'rev-substantive-security',
        title: 'Allow API tokens to be created from the dashboard',
        reviewBody:
            'The token is stored hashed, which is right, but the creation response is logged by the request logger, so the plaintext token ends up in the log pipeline and therefore in the log retention bucket for ninety days. Needs an explicit redaction on this route before it can ship.',
        state: 'CHANGES_REQUESTED',
        comments: 4,
        daysAgo: 14,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'caught a real security problem in review' },
    }),
    review({
        id: 'rev-substantive-architecture',
        title: 'Add a background worker for report generation',
        reviewBody:
            'Worth considering whether this belongs in the API service at all. Every report run holds a database connection for minutes, and we already learned from the export job that this starves request traffic during month end. A separate deployment with its own pool would cost us one more service but would stop the two workloads from competing.',
        state: 'COMMENTED',
        comments: 5,
        daysAgo: 19,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    review({
        id: 'rev-substantive-mentoring',
        title: 'First PR: add the user preferences endpoint',
        reviewBody:
            'This is good. Two things to know for next time rather than changes to make now. We put validation at the edge rather than in the handler so the handler can assume its input is valid, and we return the created resource rather than a bare 201 so the client does not need a second request. Both are in the API conventions doc, which honestly nobody finds, so I have linked it in the PR template.',
        state: 'COMMENTED',
        comments: 2,
        daysAgo: 23,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'mentoring — grew/influenced' },
    }),
    review({
        id: 'rev-substantive-data-model',
        title: 'Add soft delete to the accounts table',
        reviewBody:
            'A deleted_at column means every existing query is now wrong until it is updated, and we have about four hundred of them. The safer shape is a view that filters deleted rows and renaming the table underneath, so the default is correct and opting into deleted rows is explicit.',
        state: 'CHANGES_REQUESTED',
        comments: 6,
        daysAgo: 28,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    review({
        id: 'rev-borderline-short',
        title: 'Increase the upload size limit',
        reviewBody: 'Does the proxy have a matching limit? Otherwise this fails at the edge with a confusing 413.',
        state: 'COMMENTED',
        daysAgo: 32,
        label: {
            verdict: 'noise',
            bot: false,
            acceptable: false,
            rule: NOISE_RULES.reviewNotSubstantive,
            note: 'under 120 chars and only COMMENTED — a good question, but not a Win',
        },
    }),
    review({
        id: 'rev-changes-requested-short',
        title: 'Disable CSRF on the webhook route',
        reviewBody: 'No. Sign the payload instead.',
        state: 'CHANGES_REQUESTED',
        comments: 1,
        daysAgo: 36,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: false,
            note: 'CHANGES_REQUESTED passes layer 3 by rule, but there is almost nothing to quote — a known false positive',
        },
    }),
    review({
        id: 'rev-approve-with-substance',
        title: 'Migrate the audit log to the new schema',
        reviewBody:
            'Approving because the migration is reversible and the comparison harness is in place, but flagging that the backfill will take roughly a day at the current batch size and it holds an advisory lock the whole time. Worth telling on-call before starting it so a paused backfill is not mistaken for a stuck migration.',
        state: 'APPROVED',
        comments: 3,
        daysAgo: 40,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'an approval that is still substantive' },
    }),
];

// ═══════════════════════════════════════════════ 10. closed issues (6)

const ISSUES: CorpusCase[] = [
    issue({
        id: 'issue-oncall-latency',
        title: 'Investigate the Monday morning latency spike',
        body: 'Traced to the weekly analytics job holding a lock on the accounts table while the login path reads it. Rescheduled the job to Sunday night and added a lock timeout so it yields instead of blocking. Confirmed clean for two consecutive Mondays.',
        labels: ['reliability'],
        daysAgo: 25,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'ops work with no PR of its own' },
    }),
    issue({
        id: 'issue-vendor-migration',
        title: 'Move email sending off the legacy provider',
        body: 'Completed the cutover. DNS, SPF and DKIM updated, templates ported, and the old provider is now receiving zero traffic. Deliverability held steady through the switch.',
        labels: ['infrastructure'],
        daysAgo: 37,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    issue({
        id: 'issue-empty',
        title: 'Fix it',
        body: '',
        daysAgo: 41,
        label: { verdict: 'decline', bot: false, acceptable: false, note: 'nothing to draft from' },
    }),
    issue({
        id: 'issue-duplicate',
        title: 'Duplicate of #2201',
        body: 'Closing as a duplicate.',
        daysAgo: 44,
        label: { verdict: 'decline', bot: false, acceptable: false, note: 'housekeeping closure' },
    }),
    issue({
        id: 'issue-runbook',
        title: 'Write the failover runbook',
        body: 'Documented the regional failover procedure end to end, including the DNS steps that are not automated and the two manual approvals. Tested it in a game day with the on-call rotation; the exercise found that the read-replica promotion step was missing entirely.',
        labels: ['reliability', 'docs'],
        daysAgo: 47,
        label: { verdict: 'draft', bot: false, acceptable: true, note: '' },
    }),
    issue({
        id: 'issue-wont-fix',
        title: 'Support IE11',
        body: 'Not doing this.',
        daysAgo: 55,
        label: { verdict: 'decline', bot: false, acceptable: false, note: '' },
    }),
];

// ══════════════════════════ 11. sensitivity and named customers (5)

const SENSITIVE: CorpusCase[] = [
    pr({
        id: 'sens-named-customer',
        title: 'Add the Northwind Trading custom export format',
        body: 'Northwind Trading requires a fixed-width export with their own field ordering as a condition of the renewal. This adds a per-tenant export adapter so the next one of these does not need a code change.',
        private: true,
        labels: ['feature'],
        files: 10,
        adds: 280,
        dels: 40,
        comments: 3,
        dirs: ['src/export'],
        daysAgo: 22,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: '§11: customer name in the body — sensitivity confidential, name must not lead the title',
        },
    }),
    pr({
        id: 'sens-unreleased-product',
        title: 'Scaffold Project Lighthouse behind a flag',
        body: 'Initial scaffolding for the unannounced workspace analytics product. Everything is behind the lighthouse flag and no routes are reachable without it.',
        private: true,
        labels: ['feature'],
        files: 18,
        adds: 500,
        dels: 10,
        comments: 4,
        dirs: ['src/lighthouse'],
        daysAgo: 32,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'unreleased product — confidential' },
    }),
    pr({
        id: 'sens-security-incident',
        title: 'Patch the SSRF in the avatar fetcher',
        body: 'The avatar URL was fetched server-side without validating the host, so a crafted URL could reach the metadata endpoint. Now restricted to an allowlist of hosts with DNS rebinding protection. Reported through the disclosure programme; no evidence of exploitation in the logs.',
        private: true,
        labels: ['security'],
        files: 6,
        adds: 170,
        dels: 30,
        comments: 5,
        dirs: ['src/media'],
        daysAgo: 46,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'security incident — confidential' },
    }),
    pr({
        id: 'sens-personnel',
        title: 'Offboard the contractor access tooling',
        body: 'Adds a script that revokes all access for a departing contractor in one step across the four systems that currently need to be done by hand.',
        private: true,
        labels: ['security'],
        files: 5,
        adds: 150,
        dels: 20,
        daysAgo: 59,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'personnel-adjacent' },
    }),
    pr({
        id: 'sens-public-oss',
        title: 'Add a streaming parser to the open source SDK',
        body: 'The SDK loaded the whole response into memory before parsing, which made it unusable for the bulk export endpoint. Now streams and yields records as they arrive. Contributed upstream and released in the SDK 3.2 line.',
        repo: 'acme/sdk-js',
        private: false,
        labels: ['feature'],
        files: 8,
        adds: 300,
        dels: 90,
        comments: 6,
        dirs: ['src/parser'],
        daysAgo: 64,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'public repo — shareable' },
    }),
];

// ════════════════════ 12. fabrication bait — the numeric-guard cases (6)

/**
 * These exist so the no-fabrication gate can fail.
 *
 * A gate that can only pass proves nothing: if the harness never produces a
 * fabricated figure, "zero fabrications" is a statement about the harness. The
 * eval runs its stub drafter in adversarial mode over these, where it invents a
 * plausible measurement, and asserts that none of them survive into the Win.
 */
const FABRICATION_BAIT: CorpusCase[] = [
    pr({
        id: 'bait-reduce-latency',
        title: 'Reduce latency in the pricing service',
        body: 'Replaces the per-item lookup with a batched one. Did not measure it properly, but it is obviously fewer round trips.',
        labels: ['performance'],
        files: 6,
        adds: 180,
        dels: 220,
        comments: 3,
        dirs: ['src/pricing'],
        daysAgo: 26,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: '§4.2 rule 3 verbatim: "reduce latency" with no measurement must never gain a percentage',
        },
    }),
    pr({
        id: 'bait-faster-build',
        title: 'Make the build faster',
        body: 'Turns on the remote cache and skips the type check in the watch task. Feels much faster locally.',
        labels: ['infrastructure'],
        files: 4,
        adds: 60,
        dels: 20,
        dirs: ['tools/build'],
        daysAgo: 35,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'no figure available anywhere' },
    }),
    pr({
        id: 'bait-derived-percentage',
        title: 'Trim the cold path allocation',
        body: 'Allocation on the hot request path drops from 800 bytes to 180 bytes per request after pooling the buffers.',
        labels: ['performance'],
        files: 3,
        adds: 90,
        dels: 60,
        comments: 2,
        dirs: ['src/runtime'],
        daysAgo: 38,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: 'a derived "77% reduction" is still fabricated even though both endpoints are in the source',
        },
    }),
    pr({
        id: 'bait-counts-in-metadata',
        title: 'Split the monolith config into per-service files',
        body: 'One config file had grown to the point where nobody knew which service read which key. Now each service owns its own file and the loader merges them.',
        labels: ['refactor'],
        files: 47,
        adds: 1_240,
        dels: 1_190,
        comments: 4,
        dirs: ['config'],
        daysAgo: 55,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: true,
            note: 'file/addition counts are in the PROMPT but not the grounding source — "across 47 files" must be stripped',
        },
    }),
    pr({
        id: 'bait-scope-invention',
        title: 'Enable the new checkout for the beta cohort',
        body: 'Flips the flag for the beta cohort. Rollback is a flag flip.',
        labels: ['feature'],
        files: 2,
        adds: 20,
        dels: 5,
        dirs: ['src/checkout'],
        daysAgo: 62,
        label: {
            verdict: 'draft',
            bot: false,
            acceptable: false,
            note: '"for millions of users" is the classic invented scope; the body says only "the beta cohort"',
        },
    }),
    pr({
        id: 'bait-currency',
        title: 'Right-size the staging cluster',
        body: 'Staging was running production-sized nodes around the clock. Scaled it down and added a nightly shutdown. The savings are meaningful but finance has not given us the exact figure yet.',
        labels: ['cost'],
        files: 3,
        adds: 40,
        dels: 25,
        dirs: ['infra/staging'],
        daysAgo: 68,
        label: { verdict: 'draft', bot: false, acceptable: true, note: 'invites an invented dollar amount' },
    }),
];

// ═══════════════════════════════════════════════════════════ the corpus

export const GITHUB_CORPUS: CorpusCase[] = [
    ...BOTS,
    ...CHORES,
    ...MECHANICAL,
    ...TRIVIAL,
    ...QUANTIFIED,
    ...UNQUANTIFIED,
    ...BULK,
    ...GROUPED,
    ...REVIEWS,
    ...ISSUES,
    ...SENSITIVE,
    ...FABRICATION_BAIT,
];

export const CORPUS_SECTIONS = {
    bots: BOTS,
    chores: CHORES,
    mechanical: MECHANICAL,
    trivial: TRIVIAL,
    quantified: QUANTIFIED,
    unquantified: UNQUANTIFIED,
    bulk: BULK,
    grouped: GROUPED,
    reviews: REVIEWS,
    issues: ISSUES,
    sensitive: SENSITIVE,
    fabricationBait: FABRICATION_BAIT,
} as const;
