'use server';

/**
 * Chat server actions (docs/prd/10-chat.md).
 *
 * Convention order: Clerk `auth()` → flag → zod → rate limit → work → `Result`.
 * Metering is not here: each action the router picks charges inside the
 * service it calls, the same as on that service's own page.
 *
 * Card buttons go through these actions rather than the Scout and inbox ones,
 * so the chat works for anyone with the `chat` flag, whatever else is on.
 */

import { auth } from '@clerk/nextjs/server';
import { z } from 'zod';
import { isEnabled } from '@/lib/flags';
import { checkChatRateLimit } from '@/lib/rateLimit';
import { err, ok, type Result } from '@/lib/result';
import { prisma } from '@/lib/prisma';
import { CHAT_MESSAGE_MAX } from '@/lib/chat/router';
import { buildChatContext } from '@/lib/chat/context';
import { suggestionsFor, type ChatSuggestion } from '@/lib/chat/suggestions';
import type { ChatCard, ChatMessageView } from '@/lib/chat/types';
import { listThread, sendChatMessage as sendChatMessageCore, type SendResult } from '@/services/chat';
import { getScoutRun } from '@/services/scout';
import { confirmWinForUser, dismissWinForUser } from '@/services/wins';

type Gate = { userId: string } | { error: Result<never> };

async function gate(): Promise<Gate> {
    const { userId } = await auth();
    if (!userId) return { error: err('Not signed in', 'unauthenticated') };
    if (!(await isEnabled(userId, 'chat'))) return { error: err('Chat is not available yet', 'not_available') };
    return { userId };
}

const IdSchema = z.string().min(1).max(64);

export type ChatThread = { messages: ChatMessageView[]; suggestions: ChatSuggestion[] };

export async function getChatThread(): Promise<Result<ChatThread>> {
    const g = await gate();
    if ('error' in g) return g.error;
    const [messages, context] = await Promise.all([listThread(g.userId), buildChatContext(g.userId)]);
    return ok({ messages, suggestions: suggestionsFor(context) });
}

const SendSchema = z.object({
    text: z.string().trim().min(1).max(CHAT_MESSAGE_MAX),
    /** Generated by the browser per message, so a double submit is one message. */
    clientId: z.string().min(8).max(64),
});

export async function sendChatMessage(input: z.infer<typeof SendSchema>): Promise<Result<SendResult>> {
    const g = await gate();
    if ('error' in g) return g.error;
    const parsed = SendSchema.safeParse(input);
    if (!parsed.success) return err(`Keep it under ${CHAT_MESSAGE_MAX.toLocaleString('en-US')} characters`, 'invalid_input');
    const limited = await checkChatRateLimit(g.userId);
    if (!limited.allowed) return err(limited.error ?? 'Too many messages', 'rate_limited');
    return sendChatMessageCore({ userId: g.userId, text: parsed.data.text, clientId: parsed.data.clientId });
}

// ───────────────────────────────────────────────────────────── card refresh

/** Re-read a card whose state changes after it was sent (a run, a generation). */
export async function refreshChatCard(card: ChatCard): Promise<Result<ChatCard>> {
    const g = await gate();
    if ('error' in g) return g.error;

    if (card.type === 'scout_run') {
        if (!IdSchema.safeParse(card.runId).success) return err('Invalid card', 'invalid_input');
        const run = await getScoutRun(g.userId, card.runId);
        if (!run.success) return run;
        return ok({ ...card, status: run.data.status, kind: run.data.kind, headline: run.data.headline });
    }

    if (card.type === 'generation') {
        if (!IdSchema.safeParse(card.sessionId).success) return err('Invalid card', 'invalid_input');
        const session = await prisma.generationSession.findFirst({
            where: { id: card.sessionId, userId: g.userId },
            select: { status: true, sourceResumeId: true, resultResumeId: true },
        });
        if (!session) return err('Not found', 'not_found');
        const status = session.status === 'completed'
            ? 'completed'
            : session.status === 'awaiting_clarification' ? 'awaiting_clarification' : 'generating';
        return ok({ ...card, status, resumeId: session.resultResumeId ?? session.sourceResumeId ?? card.resumeId });
    }

    return ok(card);
}

// ───────────────────────────────────────────────────────────── Win drafts

/** The tap that writes Evidence + ClaimLink (rule 5). Never the router. */
export async function confirmChatDraft(winId: string): Promise<Result<{ winId: string; title: string }>> {
    const g = await gate();
    if ('error' in g) return g.error;
    if (!IdSchema.safeParse(winId).success) return err('Invalid id', 'invalid_input');
    return confirmWinForUser(g.userId, winId);
}

export async function dismissChatDraft(winId: string): Promise<Result<void>> {
    const g = await gate();
    if ('error' in g) return g.error;
    if (!IdSchema.safeParse(winId).success) return err('Invalid id', 'invalid_input');
    return dismissWinForUser(g.userId, winId);
}
